# Generated by Django 4.2.3 on 2023-08-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('VideoID', models.AutoField(primary_key=True, serialize=False)),
                ('VideoTitle', models.TextField()),
                ('VideoType', models.TextField()),
                ('VideoURL', models.URLField()),
                ('VideoTranscript', models.FileField(upload_to='transcripts/csv/')),
            ],
        ),
    ]
