# Generated by Django 4.2.3 on 2023-08-07 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_topic', models.TextField()),
                ('texts', models.TextField()),
                ('chart_data', models.TextField()),
                ('word_cloud_data', models.TextField()),
                ('pie_chart_data', models.TextField()),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.video')),
            ],
        ),
    ]
