# Generated by Django 4.2.3 on 2023-08-07 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_videoresult'),
    ]

    operations = [
    ]
